# Use the Node.js base image
ARG BASE_IMAGE_BUILDER=node:20.18.1-alpine3.21
FROM $BASE_IMAGE_BUILDER as development

# Install Java (if needed for your build process)
RUN apk add openjdk17-jre>=17.0.10_p7-r0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the Vite dev server port
EXPOSE 5173

# Start the Vite dev server
CMD ["npm", "run", "dev"]