ARG BASE_IMAGE_BUILDER=node:20.18.1-alpine3.21
FROM $BASE_IMAGE_BUILDER as development

# Install Java
RUN apk add openjdk17-jre>=17.0.10_p7-r0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
WORKDIR /app
COPY tsconfig*.json ./
COPY package*.json ./
COPY vite*.ts ./
COPY index.html ./
COPY env*.ts ./
COPY src/ src/
COPY public/ public/

# Install dependencies
RUN npm ci

# Expose the Vite dev server port
EXPOSE 5173

# Start the Vite dev server
CMD ["npm", "run", "dev"]