
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      automountServiceAccountToken: false
      restartPolicy: {{ .Values.restartPolicy  }}
      containers:
        - name: {{ template "common.names.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: {{ .Values.containerPorts.name }} 
              containerPort: {{ .Values.containerPorts.http }} 
              protocol: TCP
