
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
      {{- include "common.labels" . | nindent 8 }}
      app.kubernetes.io/component: client
    spec:
      restartPolicy: {{ .Values.restartPolicy  }}
      containers:
        - name: {{ template "common.names.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy | quote }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources: {{- toYaml .Values.containerResources | nindent 12 }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}

          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- else if ne .Values.resourcesPreset "none" }}
          {{- end }}
          ports:
            - name: {{ .Values.containerPorts.name }} 
              containerPort: {{ .Values.containerPorts.http }} 
              protocol: TCP
      
