{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.releasename" . }}
  labels:
    app.kubernetes.io/name: {{ template "schulportal-client.name" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{.Values.frontendHostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "schulportal-client.serviceName" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}