apiVersion: v1
kind: Service
metadata:
  name: {{ include "schulportal-client.serviceName" . }}
  labels:
    app: {{ template "schulportal-client.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ template "schulportal-client.name" . }}
