apiVersion: apps/v1
kind: Deployment
metadata:
  name: spsh-client
  labels:
    app: spsh-client
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spsh-client
  template:
    metadata:
      name: spsh-client
      labels:
        app: spsh-client
    spec:
      containers:
        - name: spsh-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
      