apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spsh-client-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.frontendHostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spsh-client-service
                port:
                  number: 80
