{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spsh-client.ingressName" . }}
  labels:
    app: {{ template "spsh-client.name" . }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{.Values.frontendHostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spsh-client.serviceName" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}