apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.releasename" . }}
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Values.commonLabels.name }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.frontendHostname  }}
      http:
        paths:
          - path:  {{ .Values.ingress.httpRelativePath  }}
            pathType: {{ .Values.ingress.pathType }}
            backend: 
              service:
                name: {{ template "common.names.releasename" . }}
                port:
                  number: {{ .Values.ingress.portnumber }}