apiVersion: v1
kind: Service
metadata:
  name: spsh-client-service
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    app: spsh-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort