apiVersion: v1
kind: Service
metadata:
  name: {{ include "spsh-client.name" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "spsh-client.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "spsh-client.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

