apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.releasename" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.commonLabels.name }}
