apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.releasename" . }}
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Values.commonLabels.name }}
spec:
  selector:
    app.kubernetes.io/layer: {{ .Values.selector.layer }}
  type: {{ .Values.servicetype }}
  
  {{- if .Values.enabledserviceport }}
  ports: {{- toYaml .Values.ports | nindent 6 }}
  {{- end }}