replicaCount: 1
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client
  tag: ""
  pullPolicy: Always

allowPrivilegeEscalation: ""
restartPolicy: Always

service:
  type: NodePort
  targetPort: 80  
  port: 80

ingress:
  enabled: true
  className: nginx
frontendHostname: "helm.dev.spsh.dbildungsplattform.de"