replicaCount: 1
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client
  tag: ""
  pullPolicy: Always

allowPrivilegeEscalation: ""
restartPolicy: Always

containerResources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 50m
    memory: 200m

nameOverride: ""

service:
  type: NodePort
  targetPort: 80  
  port: 80

ingress:
  enabled: true
  className: nginx
frontendHostname: "helm.dev.spsh.dbildungsplattform.de"


containerSecurityContext:
  enabled: true
  runAsUser: 101
  fsGroup: 101
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  privileged: false
  capabilities:
    drop: ["ALL"] 
  seccompProfile:
    type: "RuntimeDefault"