nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

replicaCount: 1
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client
  tag: ""
  pullPolicy: Always

restartPolicy: Always

frontendHostname: ""
frontend2ndHostname: ""

containerSecurityContext:
  enabled: true
  runAsUser: 101
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 50m
    memory: 200Mi

ingress:
  # Only enable if 2nd host name is defined 
  enabled2nd: false
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: Prefix
  annotations: {}

containerPorts: 
  name: http 
  http: 8080

service:
  type: NodePort
  http:
    enabled: true
  ports:
    http: 8080 

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

podDisruptionBudget:
  enabled: true
  minAvailable: "80%"