replicaCount: 1
frontendHostname: "helm.dev.spsh.dbildungsplattform.de"
nameOverride: ""
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client:latest
<<<<<<< HEAD
=======


>>>>>>> DBP-352-Set-the-correct-Docker-Image-in-the-Helm-chart-for-each-SPSH-repository
