replicaCount: 1
namespace: ""
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client
  tag: ""
  pullPolicy: Always 

frontendHostname: "helm.dev.spsh.dbildungsplattform.de"

commonLabels:
  name: spsh-client

selector:
  layer: spsh-client
 
containerPorts:
  http: 80

restartPolicy: Always
automountServiceAccountToken: false

enabledcontainerSecurityContext: true
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  fsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  privileged: false
  capabilities:
    drop: ["NET_BIND_SERVICE"]
  seccompProfile:
    type: "RuntimeDefault"
  sysctls:
    - name: net.ipv4.ip_unprivileged_port_start
      value: "8080"


volumePermissions:
  resources:
    limits: 
      memory: "1Gi"
      cpu: "500m"
    requests: 
      memory: "1Gi"
      cpu: "500m"

enabledreadinessProbe: true
readinessProbe:
  httpGet:
    path: /
    port: 80

enabledlivenessProbe: true
livenessProbe:
  httpGet:
    path: /
    port: 80

enabledStartupProbe: true
startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30
      periodSeconds: 10

ingress:
  ingressClassName: nginx
  pathType: Prefix
  httpRelativePath: "/"
  portnumber: 80

enabledserviceport:  true
ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # The container port to which the service will forward

servicetype: NodePort
serviceName: http