# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client
  tag: ""
  pullPolicy: IfNotPresent
allowPrivilegeEscalation: ""
restartPolicy: Always


service:
  type: NodePort
  targetPort: 80  
  port: 80

ingress:
  enabled: true
frontendHostname: "helm.dev.spsh.dbildungsplattform.de"