name: Push Charts to helm-charts-registry on push to main (Merge)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'charts/**'
      - '.github/workflows/**'

concurrency:
  group: schulportal-client-chart-main
  cancel-in-progress: true

jobs:
  release:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@1.3.1
    secrets: inherit
    with:
      chart_name: spsh-client
      version_generation: short_hash